# Dockerfile.backend

FROM python:3.10-slim

WORKDIR /app

# Copy backend root files
COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "main3:app", "--host", "0.0.0.0", "--port", "8000"]
